---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsqlserverinstances.tap.terasky.com
spec:
  connectionSecretKeys:
  - provider
  - type
  - host
  - port
  - database
  - username
  - password
  group: tap.terasky.com
  names:
    kind: XSQLServerInstance
    plural: xsqlserverinstances
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: The OpenAPIV3Schema of this Composite Resource Definition.
            properties:
              storageGB:
                default: 10
                enum:
                - 10
                - 20
                - 50
                description: The desired storage capacity of the database, in Gigabytes.
                type: integer
            type: object
        type: object
    served: true
