---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: rabbitmq
spec:
  description:
    short: RabbitMQ
  provisioner:
    crossplane:
      compositeResourceDefinition: xrabbitmqclusters.tap.terasky.com
