---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xrabbitmqclusters.tap.terasky.com
spec:
  connectionSecretKeys:
  - host
  - password
  - port
  - provider
  - type
  - username
  group: tap.terasky.com
  names:
    kind: XRabbitmqCluster
    plural: xrabbitmqclusters
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: The OpenAPIV3Schema of this Composite Resource Definition.
            properties:
              replicas:
                description: The desired number of replicas forming the cluster
                type: integer
                default: 3
                enum:
                - 1
                - 3
                - 5
              storageGB:
                description: The desired storage capacity of a single replica, in GB.
                type: integer
                default: 10
                enum:
                - 5
                - 10
                - 20
                - 40
                - 100
            type: object
        type: object
    served: true
